
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateEventEmitterH.js
 */
#pragma once

#include <react/renderer/components/view/ViewEventEmitter.h>


namespace facebook::react {
class ApiVideoLiveStreamViewEventEmitter : public ViewEventEmitter {
 public:
  using ViewEventEmitter::ViewEventEmitter;

  struct OnConnectionSuccess {
      
    };

  struct OnConnectionFailed {
      std::string code;
    };

  struct OnDisconnect {
      
    };

  struct OnPermissionsDenied {
      std::vector<std::string> permissions;
    };

  struct OnStartStreaming {
      int requestId;
    bool result;
    std::string error;
    };
  void onConnectionSuccess(OnConnectionSuccess value) const;

  void onConnectionFailed(OnConnectionFailed value) const;

  void onDisconnect(OnDisconnect value) const;

  void onPermissionsDenied(OnPermissionsDenied value) const;

  void onStartStreaming(OnStartStreaming value) const;
};
} // namespace facebook::react

