
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsCpp.js
 */

#include <react/renderer/components/ApiVideoLiveStreamView/Props.h>
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>

namespace facebook::react {

ApiVideoLiveStreamViewProps::ApiVideoLiveStreamViewProps(
    const PropsParserContext &context,
    const ApiVideoLiveStreamViewProps &sourceProps,
    const RawProps &rawProps): ViewProps(context, sourceProps, rawProps),

    camera(convertRawProp(context, rawProps, "camera", sourceProps.camera, {ApiVideoLiveStreamViewCamera::Back})),
    video(convertRawProp(context, rawProps, "video", sourceProps.video, {})),
    isMuted(convertRawProp(context, rawProps, "isMuted", sourceProps.isMuted, {false})),
    audio(convertRawProp(context, rawProps, "audio", sourceProps.audio, {})),
    zoomRatio(convertRawProp(context, rawProps, "zoomRatio", sourceProps.zoomRatio, {0.0})),
    enablePinchedZoom(convertRawProp(context, rawProps, "enablePinchedZoom", sourceProps.enablePinchedZoom, {false}))
      {}

} // namespace facebook::react

