
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include <react/renderer/components/ApiVideoLiveStreamView/EventEmitters.h>
#include <react/renderer/components/ApiVideoLiveStreamView/Props.h>
#include <react/renderer/components/ApiVideoLiveStreamView/States.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <jsi/jsi.h>

namespace facebook::react {

JSI_EXPORT extern const char ApiVideoLiveStreamViewComponentName[];

/*
 * `ShadowNode` for <ApiVideoLiveStreamView> component.
 */
using ApiVideoLiveStreamViewShadowNode = ConcreteViewShadowNode<
    ApiVideoLiveStreamViewComponentName,
    ApiVideoLiveStreamViewProps,
    ApiVideoLiveStreamViewEventEmitter,
    ApiVideoLiveStreamViewState>;

} // namespace facebook::react

